"""add workspaces

Revision ID: 3deb10a45af6
Revises: 5fb9ab8b0c47
Create Date: 2026-05-24 10:48:28.360752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3deb10a45af6'
down_revision: Union[str, Sequence[str], None] = '5fb9ab8b0c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pinecone_namespace', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pinecone_namespace')
    )
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('documents', 'user_id')
    op.drop_column('documents', 'pinecone_namespace')
    op.drop_column('documents', 'status')
    op.add_column('qa_responses', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_qa_responses_document_id'), table_name='qa_responses')
    op.drop_index(op.f('ix_qa_responses_user_id'), table_name='qa_responses')
    op.create_index(op.f('ix_qa_responses_workspace_id'), 'qa_responses', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('qa_responses_document_id_fkey'), 'qa_responses', type_='foreignkey')
    op.drop_constraint(op.f('qa_responses_user_id_fkey'), 'qa_responses', type_='foreignkey')
    op.create_foreign_key(None, 'qa_responses', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('qa_responses', 'user_id')
    op.drop_column('qa_responses', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_responses', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('qa_responses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'qa_responses', type_='foreignkey')
    op.create_foreign_key(op.f('qa_responses_user_id_fkey'), 'qa_responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('qa_responses_document_id_fkey'), 'qa_responses', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_qa_responses_workspace_id'), table_name='qa_responses')
    op.create_index(op.f('ix_qa_responses_user_id'), 'qa_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_qa_responses_document_id'), 'qa_responses', ['document_id'], unique=False)
    op.drop_column('qa_responses', 'workspace_id')
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('pinecone_namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_column('documents', 'workspace_id')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
